default:
    filename: 'Hagai2018_mouse-lps.rds'
    intermediaryDataFile: 'hagai_mouse_lps_data'
    resultsFile: 'hagai_mouse_lps_results'
    
    ctrl_vs_treat:
      ctrl: 'unst'
      treat: 'lps4'
      
    statTest: 't'
    
    filteringParam:
        doubletMaxPercentile: 0.95
        minGenePerCell: 300
        minCountPerCell: 500
        minCountPerGene: 200
        maxRiboPercent: 55
        maxMitoPercent: 20
        maxHbPercent: 5
    
    normMethod: 'seurat'
    
    centers: !expr matrix(c(5, -5, 5, -5, 5, 0, -10, -10), ncol = 2)
    
    computeCluster: FALSE
    
    gammas: !expr c(1, 2, 5, 10, 50, 100, 500, 2000, 10000, 20000)
    
    # Which DEs should be (re)computed
    DE:
        computeSingle: F
        computeSuper: F
        computeSingleManual: F
        computeSuperDes: F
        computeSuperEdge: F
        computePseudo: F
        computePseudoManual: F
        computeBulk: F
        computeBulkManual: F
        computeMeta: T
